language: java

jdk:
  - oraclejdk8
 
 #safelist
 branches:
  only:
  - master
  - testMaster
  
addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de

script:
- cd src/algorithm
- javac *.java
- cd ../inputOutput
- javac *.java
- cd ../mainMethod
- javac *.java
- cd ../userinterface
- javac *.java