language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - language-pack-en
      - language-pack-de
      - oracle-java8-installer

script:
- java -cp 
- cd TrackingDataAnalysisTool/src/algorithm
- javac *.java
- cd ../inputOutput
- javac *.java
- cd ../mainMethod
- javac *.java
- cd ../userinterface
- javac *.java
- cd ../sample
- javac *.java 