name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    
    strategy:
      matrix:
        java-version: [ '17', '21' ]

    steps:
    - uses: actions/checkout@v4
    
    - name: Java ${{ matrix.Java }} setup
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      
    - name: Execute Gradle build
      run: ./gradlew build
